name: stak
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - numpy
  - scipy
  - astropy
  - numpydoc
  - nbconvert>=4.2.0
  - sphinx>=1.5
  - pip:
    - sphinx_rtd_theme
    - stsci_rtd_theme

